"""Add campaign matching fields

Revision ID: eb8e79b5a1bf
Revises: 
Create Date: 2026-08-29 23:51:11.735221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8e79b5a1bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('target_country', sa.String(length=100), nullable=True))
    op.add_column('campaigns', sa.Column('target_platform', sa.String(length=50), nullable=True))
    op.add_column('campaigns', sa.Column('min_followers', sa.BigInteger(), nullable=True))
    op.add_column('campaigns', sa.Column('max_followers', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'max_followers')
    op.drop_column('campaigns', 'min_followers')
    op.drop_column('campaigns', 'target_platform')
    op.drop_column('campaigns', 'target_country')
    # ### end Alembic commands ###
